name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: build x64
      run: g++ main.cpp -o doshare
    - uses: pguyot/arm-runner-action@v2
      with:
          base_image: raspios_lite:2022-04-04
          commands: |
            test `uname -m` = ${{ matrix.arch }}
            grep Model /proc/cpuinfo
            
    - name: build arm
      run:  g++ main.cpp -o doshare_arm
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.3
      with:
        path: doshare
        
