name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: build
      run: g++ main.cpp -o doshare
    - name: Upload a Build Artifact
          
      uses: actions/upload-artifact@v4.3.3
      with:
        path: doshare
